### ISSUE TITLE
DBmodule/ accessor migration doesn't work

### ISSUE THREAD

**Issue by jdifuria** [ChicoState/radioSTAR#58]
DBmodule does not create an object that has the ability to call accessor functions in the syntax defined.

<pre>
DBmodule.displayDjs();
^

ReferenceError: DBmodule is not defined
    at Object.<anonymous> (/Users/Jay/github/radioSTAR/server.js:104:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
</pre>

**Comment by jdifuria** [comment]
all is well. Naming convention changed
